on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      compiler:
        required: true
        type: string
      build_type:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Test configurations
        run: echo "os:" ${{ inputs.os }} ", compiler:" ${{ inputs.compiler }} ", build_type:" ${{ inputs.build_type }}
        shell: bash
