name: Test

on:
  push:
  pull_request:

jobs:
  cpp-linux-macos-windows:
    name: "C++ tests (Linux-MacOS-Windows/x64)"
    strategy:
      fail-fast: false
      matrix:
        # Building for {g++, clang++}/Linux, clang++/MacOS, and msvc/Windows
        # both in Debug and Release
        build_type: [Debug, Release]
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang++
          - os: macos-latest
            compiler: clang++
          - os: windows-latest
            compiler: msvc
    runs-on: ubuntu-latest
    steps:
      - name: Test configurations
        run: echo "os:" ${{ matrix.os }} ", compiler:" ${{ matrix.compiler }} ", build_type:" ${{ matrix.build_type }}
        shell: bash
